kind = "DojoModel"
class_hash = "0x6e3fde9035218192ded3012cb7b1a36bf4d4a94c2073e158f754ffa6c43ec65"
original_class_hash = "0x6e3fde9035218192ded3012cb7b1a36bf4d4a94c2073e158f754ffa6c43ec65"
abi = "manifests/slot/abis/base/models/p_dash_models_stage_stage.json"
name = "p_dash::models::stage::stage"

[[members]]
name = "id"
type = "usize"
key = true

[[members]]
name = "x"
type = "u32"
key = false

[[members]]
name = "y"
type = "u32"
key = false

[[members]]
name = "w"
type = "u32"
key = false

[[members]]
name = "h"
type = "u32"
key = false
