services:
  pixelaw-core:
    image: ghcr.io/pixelaw/core:0.3.20
    platform: linux/x86_64
    container_name: pixelaw-core
    environment:
      - DISABLE_FEE=true
      - DISABLE_VALIDATE=true
      - RUST_LOG=info,hyper=off
#      - WORLD_ADDRESS=0xfc685b398bc4692ab3a4acd380859e71f97d2c319f188854d3a01948ba276a
      - WORLD_ADDRESS=0xfc685b398bc4692ab3a4acd380859e71f97d2c319f188854d3a01948ba276a
      - INVOKE_MAX_STEPS=4000000
    ports:
      - "127.0.0.1:5050:5050"
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9090:9090"
    restart: unless-stopped
    networks:
      - pixelaw
    volumes:
      - storage:/keiko/storage
      - log:/keiko/log
#      - ./.core/storage:/keiko/storage
#      - ./.core/log:/keiko/log
networks:
  pixelaw:
    driver: bridge
volumes:
  storage:
  log:
